### ISSUE TITLE
编码问题导致程序运行失败

### ISSUE THREAD

**Issue by LandGrey** [Cryin/JavaID#1]
直接指定源码目录运行，报错：
 File "*****\JavaID\javaid.py", line 153, in banner
    print "[-]銆怞avaID銆?Danger function identify tool"
IOError: [Errno 0] Error

解决方法：字符串前加u字修饰.
改成：
第69行            print u"[-]【JavaID】identify danger function Finished!"
第74行            print u"[+]【" + vul + u"】identify danger function [" + self._function + u"] in file [" + self._filename + u"]"
第153行         print u"[-]【JavaID】 Danger function identify tool"

**Comment by Cryin** [comment]
good job！
